name: CI
on: [push, pull_request]

jobs:
  checks:
    name: Checks
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - run: cargo check --examples --tests --all-targets
      - run: cargo fmt --all -- --check --files-with-diff
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo test --all-features

  deny:
    name: Deny
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: EmbarkStudios/cargo-deny-action@v1
